apiVersion: instancemgr.orkaproj.io/v1alpha1
kind: InstanceGroup
metadata:
  name: hello-world
spec:
  provisioner: eks-cf
  strategy:
    type: crd
    crd:
      crdName: rollups
      statusJSONPath: .status.currentStatus
      statusSuccessString: completed
      statusErrorString: error
      spec: |
        apiVersion: asgtools.intuit.k8s.io/v1beta1
        kind: Rollup
        metadata:
          labels:
            controller-tools.k8s.io: "1.0"
          name: rollup-nodes
        spec:
          postDrainDelaySeconds: 90
          nodeIntervalSeconds: 300
          asgName: {{ .InstanceGroup.Status.ActiveScalingGroupName }}
          postDrainScript: |
              set -ex
              echo "Hello, postDrain!"
          postWaitScript: |
              echo "Hello, postWait"
          postTerminateScript: |
              echo "Hello, postTerminate!"
  eks-cf:
    minSize: 1
    maxSize: 3
    configuration:
      bootstrapArguments: --register-with-taints=my-taint-key=my-taint-value:NoSchedule --node-labels=my-label=true
      keyPairName: my-key
      image: ami-089d3b6350c1769a6
      instanceType: m5.large
      volSize: 20
      clusterName: my-eks-cluster
      subnets:
      - subnet-1a2b3c4d
      - subnet-4d3c2b1a
      - subnet-0w9x8y7z
      securityGroups:
      - sg-q1w2e3r4t5y6u7i8
      tags:
        - key: mykey
          value: myvalue