apiVersion: instancemgr.orkaproj.io/v1alpha1
kind: InstanceGroup
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: bdd-test-crd
  namespace: instance-manager
spec:
  provisioner: eks-cf
  strategy:
    type: crd
    crd:
      crdName: workflows
      statusJSONPath: .status.phase
      statusSuccessString: Succeeded
      statusErrorString: Failed
      spec: |
        apiVersion: argoproj.io/v1alpha1
        kind: Workflow
        metadata:
          name: bdd-test
          namespace: instance-manager
        spec:
          entrypoint: whalesay
          templates:
          - name: whalesay
            container:
              image: docker/whalesay
              command: [cowsay]
              args: ["hello world"]
              resources:
                limits:
                  memory: 32Mi
                  cpu: 100m
  eks-cf:
    maxSize: 6
    minSize: 3
    configuration:
      bootstrapArguments: --register-with-taints=node-role.kubernetes.io/bdd-test=bdd-test:NoSchedule --node-labels=test-label.kubernetes.io/a-label=true
      clusterName: {{ .ClusterName }}
      subnets: {{ .Subnets }}
      keyPairName: {{ .KeyPairName }}
      vpcId: {{ .VpcID }}
      image: {{ .AmiID }}
      instanceType: m3.medium
      volSize: 20
      securityGroups: {{ .NodeSecurityGroups }}
      tags:
        - key: mykey
          value: myvalue